# This PodGangSet definition explicitly sets the startup order of the cliques.
# Startup order is observed amongst the PodCliques that are part of a PodGang that is created for a PodGangSet.
# In the example below, the following startup order is expected for every PodGang that is created for this PodGangSet.
# 1. pca (this is the first clique to start)
# 2. pcb, pcc (these two cliques will start in parallel after pca)
# 3. pcd (this clique will start after pcb and pcc)
#
# To verify the startup order, you can inspect the following:
# - For each Pod belonging to a PodClique, check the `LastTransitionTime` of the Pod's `Ready` condition.
#   The `LastTransitionTime` should reflect the order in which the Pods became ready.
# - In addition, you can check the logs of the last `InitContainer` of each Pod to get the details of dependency handling.
---
apiVersion: grove.io/v1alpha1
kind: PodGangSet
metadata:
  name: simple2
  labels:
    app: simple2
spec:
  replicas: 1
  template:
    terminationDelay: 1m
    cliqueStartupType: CliqueStartupTypeExplicit # To ensure that the startup order as defined in this spec is honored, the statupType must be set to Explicit.
    cliques:
      # pca is the first clique to start. For this clique the startsAfter will be empty.
      - name: pca
        spec:
          roleName: rolea
          replicas: 3
          podSpec:
            containers:
              - name: pca
                image: nginx:latest
                resources:
                  requests:
                    cpu: 10m
          autoScalingConfig:
            maxReplicas: 5
            metrics:
              - type: Resource
                resource:
                  name: cpu
                  target:
                    type: Utilization
                    averageUtilization: 80
      # pcb depends on pca, its startsAfter will be set to pca.
      - name: pcb
        spec:
          roleName: roleb
          startsAfter:
            - pca
          replicas: 2
          podSpec:
            containers:
              - name: pcb
                image: nginx:latest
                resources:
                  requests:
                    cpu: 10m
      # pcc depends on pca, its startsAfter will be set to pca.
      - name: pcc
        spec:
          roleName: rolec
          startsAfter:
            - pca
          replicas: 2
          podSpec:
            containers:
              - name: pcc
                image: nginx:latest
                resources:
                  requests:
                    cpu: 10m
      # pcd depends on pcb and pcc, its startsAfter will be set to pcb, pcc
      - name: pcd
        spec:
          roleName: roled
          startsAfter:
            - pcb
            - pcc
          replicas: 2
          podSpec:
            containers:
              - name: pcd
                image: nginx:latest
                resources:
                  requests:
                    cpu: 10m