apiVersion: core.grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: my-inference-cluster
  namespace: default
spec:
  replicas: 3
  
  # Top-level: Controls how PCS replicas are updated
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Update one PCS replica at a time
      maxSurge: 0        # Don't create extra replicas (avoids index holes)
  
  template:
    cliques:
      # Standalone PodClique: Frontend (needs zero downtime)
      - name: frontend
        spec:
          roleName: frontend
          replicas: 5
          minAvailable: 5
          podSpec:
            containers:
              - name: frontend
                image: frontend:v2
        # Component-level: How pods within this PodClique update
        updateStrategy:
          maxUnavailable: 0  # Never take down a pod
          maxSurge: 1        # Create new pod before deleting old one
      
      # Standalone PodClique: Backend (can tolerate some downtime)
      - name: backend
        spec:
          roleName: backend
          replicas: 3
          minAvailable: 2
          podSpec:
            containers:
              - name: backend
                image: backend:v2
        # Component-level: Faster updates acceptable
        updateStrategy:
          maxUnavailable: 1  # Standard rolling update
          maxSurge: 0
    
    # PodCliqueScalingGroup: Prefill workers
    podCliqueScalingGroups:
      - name: prefill
        replicas: 4
        minAvailable: 2
        cliqueNames:
          - prefill-leader
          - prefill-workers
        # Component-level: How PCSG replicas update
        updateStrategy:
          maxUnavailable: 2  # Can update 2 prefill replicas concurrently
          maxSurge: 0
      
      # PodCliqueScalingGroup: Decode workers (more conservative)
      - name: decode
        replicas: 3
        minAvailable: 1
        cliqueNames:
          - decode-leader
          - decode-workers
        # Component-level: One decode replica at a time
        updateStrategy:
          maxUnavailable: 1
          maxSurge: 0

---
# Example: ReplicaRecreate strategy (tear down entire replica)
apiVersion: core.grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: batch-processing
  namespace: default
spec:
  replicas: 2
  
  # Top-level: Recreate entire replicas
  updateStrategy:
    type: ReplicaRecreate
    # Note: rollingUpdate field is ignored for ReplicaRecreate
    # Component-level strategies are also bypassed
  
  template:
    cliques:
      - name: worker
        spec:
          roleName: worker
          replicas: 10
          minAvailable: 8
          podSpec:
            containers:
              - name: worker
                image: worker:v3
        # This updateStrategy is ignored when PCS uses ReplicaRecreate
        updateStrategy:
          maxUnavailable: 1
          maxSurge: 0

---
# Example: OnDelete strategy (manual updates only)
apiVersion: core.grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: stateful-service
  namespace: default
spec:
  replicas: 3
  
  # Top-level: Manual update control
  updateStrategy:
    type: OnDelete
    # Replicas only update when manually deleted
  
  template:
    cliques:
      - name: database
        spec:
          roleName: database
          replicas: 1
          minAvailable: 1
          podSpec:
            containers:
              - name: postgres
                image: postgres:16
        # Component strategies still apply once a replica starts updating
        updateStrategy:
          maxUnavailable: 0
          maxSurge: 1  # Ensure zero downtime when manually triggered

