apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ required ".Values.clusterRoleBinding.name is required" .Values.clusterRoleBinding.name }}
  labels:
{{- include "kube-scheduler.clusterrolebinding.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ required ".Values.serviceAccount.name is required" .Values.serviceAccount.name }}
  namespace: {{ required ".Values.serviceAccount.namespace is required" .Values.serviceAccount.namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ required ".Values.clusterRoleBinding.name is required" .Values.clusterRoleBinding.name }}-volume-scheduler
  labels:
{{- include "kube-scheduler.clusterrolebinding.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ required ".Values.serviceAccount.name is required" .Values.serviceAccount.name }}
  namespace: {{ required ".Values.serviceAccount.namespace is required" .Values.serviceAccount.namespace }}
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
