apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required ".Values.configMap.name is required" .Values.configMap.name }}
  namespace: {{ required ".Values.configMap.namespace is required" .Values.configMap.namespace }}
  labels:
{{- include "kube-scheduler.serviceaccount.labels" . | nindent 4 }}
data:
  scheduler-configuration.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: {{ required ".Values.schedulerName is required" .Values.schedulerName }}
    leaderElection:
      leaderElect: false
