apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required ".Values.configMap.name is required" .Values.configMap.name }}
  namespace: {{ required ".Values.configMap.namespace is required" .Values.configMap.namespace }}
  labels:
{{- include "kube-scheduler.serviceaccount.labels" . | nindent 4 }}
data:
{{- $configFileName := required ".Values.config.configFile.name is required" .Values.config.configFile.name }}
  {{ $configFileName }}: |
{{- toYaml .Values.config.schedulerConfiguration | nindent 4 }}
