apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{- include "kube-scheduler.deployment.labels" . | nindent 4 }}
  name: {{ required ".Values.deployment.name is required" .Values.deployment.name }}
  namespace: {{ required ".Values.deployment.namespace is required" .Values.deployment.namespace }}
spec:
  selector:
    matchLabels:
{{- include "kube-scheduler.deployment.matchLabels" . | nindent 6 }}
  replicas: {{ required ".Values.replicaCount is required" .Values.replicaCount }}
  template:
    metadata:
      labels:
{{- include "kube-scheduler.deployment.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ required ".Values.serviceAccount.name is required" .Values.serviceAccount.name }}
      automountServiceAccountToken: false
      containers:
      - args:
        - --config={{ required ".Values.config.configFile.mountPath" .Values.config.configFile.mountPath }}/{{ required ".Values.config.configFile.name" .Values.config.configFile.name }}
        image: {{ include "image" .Values.image }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ required ".Values.config.livenessProbe.port is required" .Values.config.livenessProbe.port }}
            scheme: HTTPS
          initialDelaySeconds: 15
        name: {{ required ".Values.schedulerName is required" .Values.schedulerName }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ required ".Values.config.readinessProbe.port is required" .Values.config.readinessProbe.port }}
            scheme: HTTPS
        resources:
{{- toYaml .Values.config.resources | nindent 12 }}
        securityContext:
          privileged: false
        volumeMounts:
          - name: scheduler-configuration-volume
            mountPath: {{ required ".Values.config.configFile.mountPath" .Values.config.configFile.mountPath }}
      hostNetwork: false
      hostPID: false
      volumes:
        - name: scheduler-configuration-volume
          configMap:
            name: {{ required ".Values.configMap.name is required" .Values.configMap.name }}
