apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ required ".Values.roleBinding.name is required" .Values.roleBinding.name }}
  namespace: {{ required ".Values.roleBinding.namespace is required" .Values.roleBinding.namespace }}
  labels:
{{- include "kube-scheduler.rolebinding.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ required ".Values.serviceAccount.name is required" .Values.serviceAccount.name }}
  namespace: {{ required ".Values.serviceAccount.namespace is required" .Values.serviceAccount.namespace }}
