apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required ".Values.serviceAccount.name is required" .Values.serviceAccount.name }}
  namespace: {{ required ".Values.serviceAccount.namespace is required" .Values.serviceAccount.namespace }}
  labels:
{{- include "kube-scheduler.serviceaccount.labels" . | nindent 4 }}
