kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.31.1
    extraPortMappings:
      - containerPort: 4566
        hostPort: 4566
        protocol: TCP
      - containerPort: 10000
        hostPort: 10000
        protocol: TCP
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
          config_path = "/etc/containerd/certs.d"
