apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: scheduler
build:
  local: # see https://skaffold.dev/docs/builders/build-environments/local/
    push: true
  artifacts:
    - image: local-skaffold/kube-scheduler
      ko: # see https://skaffold.dev/docs/builders/builder-types/ko/
        dependencies:
          paths:
            - cmd
            - plugins/grovescheduling
            - internal
            - VERSION
        flags:
          - -v
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd
# Deploy will only be used to run the scheduler as the second scheduler
deploy:
  helm: # see https://skaffold.dev/docs/deployers/helm/
    releases:
      - name: grove-kube-scheduler
        chartPath: charts
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_kube_scheduler}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_kube_scheduler}}@{{.IMAGE_DIGEST_local_skaffold_kube_scheduler}}'
        skipBuildDependencies: true
        createNamespace: true
        wait: false
profiles:
  - name: debug
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          replicaCount: 1
          config.leaderElection.enabled: false
