apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: single-node-aggregated
  namespace: default
spec:
  replicas: 1
  template:
    cliques:
    - name: model-worker
      spec:
        roleName: model-worker
        replicas: 2
        podSpec:
          tolerations:
          - key: fake-node
            operator: Equal
            value: "true"
            effect: NoSchedule
          containers:
          - name: model-worker
            image: nginx:latest
            command: ["/bin/sh"]
            args: ["-c", "echo 'Model Worker (Aggregated) on node:' && hostname && sleep 3600"]
            resources:
              requests:
                cpu: "1"
                memory: "2Gi"