apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ required ".Values.clusterRole.name is required" .Values.clusterRole.name }}
  labels:
{{- include "operator.clusterrole.labels" . | nindent 4 }}
rules:
- apiGroups:
  - scheduler.grove.io
  resources:
  - podgangs
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - grove.io
  resources:
  - podgangsets
  - podgangsets/status
  - podcliques
  - podcliques/status
  - podcliquescalinggroups
  - podcliquescalinggroups/status
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - delete
  - deletecollection
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - get
  - list
  - delete
  - deletecollection
  - patch
  - update
  - watch

