apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ required ".Values.clusterRole.name is required" .Values.clusterRole.name }}
  labels:
{{- include "operator.clusterrole.labels" . | nindent 4 }}
rules:
- apiGroups:
  - grove.io
  resources:
  - podgangsets
  - podgangsets/status
  - podcliques
  - podcliques/status
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
  - patch
