apiVersion: apps/v1
kind: Deployment
metadata:
  name: grove-operator
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "operator.deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ required ".Values.replicaCount is required" .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "operator.deployment.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "operator.deployment.labels" . | nindent 8 }}
    spec:
      {{- if .Values.priorityClass.enabled }}
      priorityClassName: {{ required ".Values.priorityClass.name is required" .Values.priorityClass.name }}
      {{- end }}
      serviceAccountName: {{ required ".Values.serviceAccount.name is required" .Values.serviceAccount.name }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: grove-operator
          image: {{ include "image" .Values.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config=/etc/grove-operator/config/config.yaml
          {{- if .Values.config.server.healthProbes.enable }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ required ".Values.config.server.healthProbe.port is required" .Values.config.server.healthProbes.port }}
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ required ".Values.config.server.healthProbe.port is required" .Values.config.server.healthProbes.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
          {{- end }}
          {{- if .Values.resources }}
{{- toYaml .Values.resources | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: operator-config
              mountPath: /etc/grove-operator/config
            - name: kube-api-access-grove
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            {{- if .Values.webhooks.podgangsetValidationWebhook.isEnabled }}
            - name: grove-webhook-server-cert
              mountPath: /etc/grove-operator/webhook-certs
              readOnly: true
            {{- end }}
      volumes:
        - name: kube-api-access-grove
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 43200 # 12 hours
              - configMap:
                  name: kube-root-ca.crt
                  items:
                  - key: ca.crt
                    path: ca.crt
        - name: operator-config
          configMap:
            name: {{ include "operator.config.name" . }}
        {{- if .Values.webhooks.podgangsetValidationWebhook.isEnabled }}
        - name: grove-webhook-server-cert
          secret:
            secretName: {{ required ".Values.webhookSeverSecret.name is required" .Values.webhookSeverSecret.name }}
            defaultMode: 420
        {{- end }}