apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required ".Values.serviceAccount.name is required" .Values.serviceAccount.name }}
  labels:
{{- include "operator.serviceaccount.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}