{{- if .Values.config.server.webhooks.certManagement.autoProvision }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.server.webhooks.certManagement.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "operator.server.secret.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
{{- end }}
