{{- if .Values.webhooks.podgangsetValidationWebhook.isEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.webhookServerSecret.name is required" .Values.webhookServerSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "operator.server.secret.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "pki-resources/server.crt" | b64enc }}
  tls.key: {{ .Files.Get "pki-resources/server.key" | b64enc }}
{{- end }}