{{- if .Values.webhooks.podgangsetValidationWebhook.isEnabled }}
{{- if .Values.enableCertManager }}
# When using cert-manager, the certificate secret is managed by cert-manager
# This template is kept for reference but the actual secret is created by cert-manager
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: grove-webhook-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "operator.server.secret.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "pki-resources/server.crt" | b64enc }}
  tls.key: {{ .Files.Get "pki-resources/server.key" | b64enc }}
{{- end }}
{{- end }}