{{- if .Values.webhooks.podgangsetValidationWebhook.isEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grove-webhook-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "operator.server.secret.labels" . | nindent 4 }}
{{- end }}