apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: grove-operator
build:
  local: # see https://skaffold.dev/docs/builders/build-environments/local/
    push: true
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
    - image: grove-operator
      ko: # see https://skaffold.dev/docs/builders/builder-types/ko/
        dependencies: # configures which files should skaffold watch for changes in dev mode.
          paths:
            - api
            - cmd
            - initc
            - internal
            - VERSION
        flags:
          - -v
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd
    - image: grove-initc
      ko: # see https://skaffold.dev/docs/builders/builder-types/ko/
        dependencies: # configures which files should skaffold watch for changes in dev mode.
          paths:
            - api
            - initc
            - internal
            - VERSION
        flags:
          - -v
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./initc/cmd
deploy:
  helm: # see https://skaffold.dev/docs/deployers/helm/
    releases:
      - name: grove-operator
        chartPath: charts
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO}}'
          image.tag: "{{.VERSION}}@{{.IMAGE_DIGEST}}"
          deployment.env:
            - name: GROVE_INIT_CONTAINER_IMAGE
              value: "{{.CONTAINER_REGISTRY}}/grove-initc"
        skipBuildDependencies: true
        createNamespace: true
        wait: true
profiles:
  - name: debug
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          replicaCount: 1
          config.leaderElection.enabled: false
