apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: grove-operator
build:
  local: { } # see https://skaffold.dev/docs/builders/build-environments/local/
  artifacts:
    - image: local-skaffold/grove-operator
      ko: # see https://skaffold.dev/docs/builders/builder-types/ko/
        fromImage: gcr.io/distroless/static-debian11:nonroot
        dependencies: # configures which files should skaffold watch for changes in dev mode.
          paths:
            - api
            - cmd
            - internal
            - go.mod
            - VERSION
        flags:
          - -v
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd
deploy:
  helm: # see https://skaffold.dev/docs/deployers/helm/
    releases:
      - name: grove-operator
        chartPath: charts
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_grove_operator}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_grove_operator}}@{{.IMAGE_DIGEST_local_skaffold_grove_operator}}'
        namespace: default
        skipBuildDependencies: true
profiles:
  - name: debug
    patches:
        - op: add
          path: /deploy/helm/releases/0/setValues/replicas
          value: 1
        - op: add
          path: /deploy/helm/releases/0/setValues/config
          value:
            leaderElection:
              enabled: false
