name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"
      - name: test-unit
        run: make test-unit
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"
      - name: build-operator
        run: make --directory=operator build-operator
      - name: build-initc
        run: make --directory=operator build-initc
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"
      - name: lint
        run: make lint
      - name: generate
        run: make generate
      - name: license
        run: make add-license-headers
      - name: format
        run: make format
      - name: api-docs
        run: make generate-api-docs
      - name: fail if git tree is dirty
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "ERROR: Git tree is dirty after running the check step."
            echo "Please check the diff to identify the step that dirtied the tree."
            git status
            git diff
            exit 1
          fi
