name: Build Operator

on: [push, pull_request]

jobs:
  build-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"
      - name: build-operator
        run: make --directory=operator build-operator
      - name: Start KIND cluster
        run: sudo make --directory=operator kind-up
      - name: Fix kubeconfig permissions
        run: sudo chown $(id -u):$(id -g) operator/hack/kind/kubeconfig && sudo chmod 644 operator/hack/kind/kubeconfig # or can chmod 777
      - name: Install CRDs required by sample (server-side apply to avoid large annotations)
        run: |
          set -euo pipefail
          KCFG=operator/hack/kind/kubeconfig
          kubectl --kubeconfig "$KCFG" apply --server-side -f operator/api/core/v1alpha1/crds/grove.io_podcliques.yaml
          kubectl --kubeconfig "$KCFG" apply --server-side -f operator/api/core/v1alpha1/crds/grove.io_podcliquescalinggroups.yaml
          kubectl --kubeconfig "$KCFG" apply --server-side -f operator/api/core/v1alpha1/crds/grove.io_podgangsets.yaml
          kubectl --kubeconfig "$KCFG" apply --server-side -f scheduler/api/core/v1alpha1/crds/scheduler.grove.io_podgangs.yaml
          kubectl --kubeconfig "$KCFG" wait --for=condition=Established \
            crd/podcliques.grove.io \
            crd/podcliquescalinggroups.grove.io \
            crd/podgangsets.grove.io \
            crd/podgangs.scheduler.grove.io \
            --timeout=120s
      - name: Apply sample manifest to KIND cluster
        run: kubectl --kubeconfig operator/hack/kind/kubeconfig apply -f operator/samples/simple/simple1.yaml
      - name: Wait for simple1 Pods to be Ready
        run: |
          set -euo pipefail
          KCFG=operator/hack/kind/kubeconfig
          NS=default
          SEL='app=simple1'
          # Wait up to 120s for pods to be created
          for i in {1..24}; do
            echo "[create-wait] Iteration $i/24 - listing pods matching $SEL in namespace $NS"
            kubectl --kubeconfig "$KCFG" -n "$NS" get pods -l "$SEL" -o wide || true
            COUNT=$(kubectl --kubeconfig "$KCFG" -n "$NS" get pods -l "$SEL" --no-headers 2>/dev/null | wc -l)
            if [ "$COUNT" -gt 0 ]; then
              break
            fi
            sleep 5
          done
          # Wait for pods to become Ready
          echo "[ready-wait] Waiting for pods with $SEL in $NS to become Ready..."
          kubectl --kubeconfig "$KCFG" -n "$NS" wait --for=condition=Ready pods -l "$SEL" --timeout=300s
          kubectl --kubeconfig "$KCFG" -n "$NS" get pods -l "$SEL" -o wide