name: Build Operator

on: [push, pull_request]

jobs:
  build-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"
      - name: build-operator
        run: make --directory=operator build-operator
      - name: Start KIND cluster
        run: sudo make --directory=operator kind-up
      - name: Fix kubeconfig permissions
        run: sudo chown $(id -u):$(id -g) operator/hack/kind/kubeconfig && sudo chmod 644 operator/hack/kind/kubeconfig
      - name: Apply sample manifest to KIND cluster
        run: kubectl --kubeconfig operator/hack/kind/kubeconfig apply -f operator/samples/simple/simple1.yaml